version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: eliza-agent-postgres
    environment:
      POSTGRES_DB: eliza_agent
      POSTGRES_USER: eliza
      POSTGRES_PASSWORD: eliza_dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 